spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ourstory_dev
    hikari:
      read-only: false
    username: root
    password: song13055523!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# mkdir -p src/main/resources/upload-dir
server:
  port: 8001
  servlet:
    context-path: "/ourstory"

logging:
  level:
    root: info
    web: info
    sql: error
    org.hibernate: error
    org.springframework: error
    studio.ourstory: info
#    org.springframework.security: DEBUG

file:
  rootDir: /Users/songjeongpyeong/Documents/GitHub/ourstory
  uploadDir: src/main/resources/upload-dir
  profileImageDir: src/main/resources/upload-dir/profileimage