spring:
  profiles: prod

server:
  port: 8000

logging:
  level:
    root: info
    web: info
    sql: error
    org.hibernate: error
    org.springframework: error


management:
  endpoints:
    web:
      exposure:
        include: health,info  # health와 info 엔드포인트를 포함합니다.

info:
  app:
    name: ourstory
    description: This is my production application.
    version: 1.0.0  # 버전 정보
    build:
      number: 1  # 빌드 번호
      time: 2024-07-16T12:00:00Z  # 빌드 시간